version: '3.8'

services:
  nodejs:
    build: .
    ports:
      - '3000:3000'
    env_file: ./.env
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/flaminGo
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./db
      dockerfile: flaminGoDB.dockerfile
